# @format
version: "3.7"

services:
  web:
    build: .
    container_name: test_deploy_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/KMPDC/
      - staticfiles:/static/
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: test_deploy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=discipline
      - POSTGRES_USER=hypertext
      - POSTGRES_PASSWORD=assassin

  nginx:
    build: ./nginx
    container_name: test_deploy_nginx
    volumes:
      - staticfiles:/static/
    ports:
      - 8008:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles:
